name: Generate Index

# Trigger on push to main or on a schedule
on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # 4. Run the Python script
    - name: Generate index.html
      run: |
        python generate_index.py

    # 5. (Optional) Commit the generated index.html back to the repo
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git diff --quiet || git commit -m "Auto-generate index.html"
        git push
      env:
        # Needed for pushing to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}