name: Generate Index

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. Install dependencies (if any)
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # 4. Run the Python script
    - name: Generate index.html
      run: python generate_index.py

    # 5. Commit and push only if index.html changed
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git diff --cached --quiet || git commit -m "Auto-generate index.html"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main